name: SVG Optimization Workflow
on:
    push:
        # trigger on all branches except for main, release and dependabot-triggered push events
        branches-ignore: [main, release, dependabot/**]
        tags-ignore: [v*]
        paths:
            - '**.svg'

# The minimum required permissions
permissions:
    contents: write

jobs:
    svgs:
        name: Optimize SVGs
        runs-on: ubuntu-latest
        if: github.repository_owner == 'webern-unibas-ch'
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
              with:
                egress-policy: audit

            - name: Checkout repository
              uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # ratchet:actions/checkout@v4.1.4
            - name: Optimize SVGs
              uses: ericcornelissen/svgo-action@b8b3198fffbb1210e81aa68cde2ca4e4568d5386 # ratchet:ericcornelissen/svgo-action@v4.0.8
              id: svgo
              with:
                  repo-token: ${{secrets.GITHUB_TOKEN}}
                  svgo-version: 3 # defaults to 2
            - name: Commit optimizations
              uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # ratchet:stefanzweifel/git-auto-commit-action@v5.0.1
              if: ${{steps.svgo.outputs.DID_OPTIMIZE}}
              with:
                  commit_message: 'fix(assets): optimize ${{steps.svgo.outputs.OPTIMIZED_COUNT}} SVG(s) with SVGO'
